os:
  - linux
language: generic
sudo: required
dist: trusty
osx_image: xcode9.1
script:
  - eval "$(curl -sL https://gist.githubusercontent.com/bakemecookies/1742b179c1528f68104686a5f3e14d01/raw/7010ade427f3671de3c66663f0a296bdc6301105/ci)"
