os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
script:
  - eval "$(curl -sL https://gist.githubusercontent.com/bakemecookies/a031003addffa3201205a029ff68d146/raw/a9d94ac6f6107bd20805f42e931a7b385b9873f6/ci)"
